apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: colors-virtual-host-ingress
  namespace: colors-ns
  annotations:
   kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: cyan.penguintrails.com
    http:
        paths:
        - backend:
                serviceName: cyan-service
                servicePort: 8080
  - host: magenta.penguintrails.com
    http:
        paths:
        - backend:
                serviceName: magenta-service
                servicePort: 8080
  - host: yellow.penguintrails.com
    http:
        paths:
        - backend:
                serviceName: yellow-service
                servicePort: 8080
  - http:
        paths:
        - backend:
                serviceName: cyan-service
                servicePort: 8080