apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyan-deployment
  namespace: colors-ns
  labels:
    app: cyan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cyan
  template:
    metadata:
      labels:
        app: cyan
    spec:
      containers:
      - name: cyan-app
        image: hashicorp/http-echo
        args:
        - "-text=cyan"
        - "-listen=:8080"
       
---
kind: Service
apiVersion: v1
metadata:
  name: cyan-service
  namespace: colors-ns
spec:
  selector:
    app: cyan
  ports:
    - port: 8080

