apiVersion: apps/v1
kind: Deployment
metadata:
  name: magenta-deployment
  namespace: colors-ns
  labels:
    app: magenta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magenta
  template:
    metadata:
      labels:
        app: magenta
    spec:
      containers:
      - name: magenta-app
        image: hashicorp/http-echo
        args:
        - "-text=magenta"
        - "-listen=:8080"
       
---
kind: Service
apiVersion: v1
metadata:
  name: magenta-service
  namespace: colors-ns
spec:
  selector:
    app: magenta
  ports:
    - port: 8080

