apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow-deployment
  namespace: colors-ns
  labels:
    app: yellow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yellow
  template:
    metadata:
      labels:
        app: yellow
    spec:
      containers:
      - name: yellow-app
        image: hashicorp/http-echo
        args:
        - "-text=yellow"
        - "-listen=:8080"
       
---
kind: Service
apiVersion: v1
metadata:
  name: yellow-service
  namespace: colors-ns
spec:
  selector:
    app: yellow
  ports:
    - port: 8080

